AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - .bundle/**/*
    - bin/**/*
    - coverage/**/*
    - vendor/**/*

Bundler/OrderedGems:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: true
  Max: 120

Metrics/ModuleLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
  Max: 25

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
  Max: 12

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false
