#!/usr/bin/env ruby
# frozen_string_literal: true

require 'ldap_account_tools'

ILLEGAL_CONFIG_ERROR_CODE = 7
TOOL_OPERATION_ERROR_CODE = 8
SIGINT_ERROR_CODE = 130

Signal.trap('INT') do |_|
  exit SIGINT_ERROR_CODE
end

begin
  LdapAccountManage.application.run
rescue LdapAccountManage::Util::ToolOperationError => err
  STDERR.puts "Error: #{err.message}"

  exit TOOL_OPERATION_ERROR_CODE
rescue LdapAccountManage::IllegalConfigError => err
  STDERR.puts "Config error: #{err.message}"

  exit ILLEGAL_CONFIG_ERROR_CODE
end
