#!/usr/bin/env ruby
# frozen_string_literal: true

require 'ldap_account_tools'
require 'net-ldap'

ILLEGAL_CONFIG_ERROR_CODE = 7
TOOL_OPERATION_ERROR_CODE = 8
CRITICAL_ERROR_CODE = 9
SIGINT_ERROR_CODE = 130

Signal.trap('INT') do |_|
  exit SIGINT_ERROR_CODE
end

begin
  LdapAccountManage.application.run
rescue LdapAccountManage::Util::ToolOperationError => e
  warn "Error: #{e.message}"

  exit TOOL_OPERATION_ERROR_CODE
rescue LdapAccountManage::IllegalConfigError => e
  warn "Config error: #{e.message}"

  exit ILLEGAL_CONFIG_ERROR_CODE
rescue Net::LDAP::Error => e
  if e.message =~ /^Cannot assign requested address/
    warn "Failed to connect LDAP: #{e.message}"

    exit CRITICAL_ERROR_CODE
  else
    pass e
  end
rescue Net::LDAP::ConnectionRefusedError => e
  warn "Failed to connect LDAP: #{e.message}"

  exit CRITICAL_ERROR_CODE
end
